default:
  image: docker
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY

variables:
  DOCKER_HOST: tcp://dind-rootless:2375
  CONTAINER_TARGET: 2.5.2
  CONTAINER_IMAGE: $CI_REGISTRY_IMAGE:$CONTAINER_TARGET

stages:
  - build

build:
  stage: build
  script:
    - docker build --pull -t $CONTAINER_IMAGE $CONTAINER_TARGET
    - docker push $CONTAINER_IMAGE

